; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl@^9.5.0
	zinggjm/GxEPD2@^1.6.8
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = dio_opi
build_flags = 
	-Os
	-DCORE_DEBUG_LEVEL=5
	-DUSER_SETUP_LOADED=1
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DST7789_DRIVER=1
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DTFT_MISO=-1
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=5
	-DTFT_DC=19
	-DTFT_RST=4
	-DTOUCH_CS=22
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=27000000
